# Generated by Django 5.2.12 on 2026-04-06 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AktaPT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pt', models.CharField(max_length=255)),
                ('kota_pt', models.CharField(blank=True, max_length=100)),
                ('alamat_pt', models.TextField(blank=True)),
                ('modal_dasar', models.BigIntegerField(default=0)),
                ('total_lembar', models.IntegerField(default=0)),
                ('kbli_json', models.TextField(default='[]')),
                ('status', models.CharField(default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'akta_pt',
            },
        ),
        migrations.CreateModel(
            name='CatatanAkta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isi', models.TextField()),
                ('selesai', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('akta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catatan_set', to='core.aktapt')),
            ],
            options={
                'db_table': 'catatan_akta',
            },
        ),
        migrations.CreateModel(
            name='Pengurus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sebutan', models.CharField(blank=True, max_length=20)),
                ('nama', models.CharField(blank=True, max_length=255)),
                ('jabatan', models.CharField(blank=True, max_length=100)),
                ('saham_persen', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('tpl', models.CharField(blank=True, max_length=100)),
                ('tgl_lahir', models.DateField(blank=True, null=True)),
                ('nik', models.CharField(blank=True, max_length=20)),
                ('pekerjaan', models.CharField(blank=True, max_length=100)),
                ('tipe_kab', models.CharField(blank=True, max_length=20)),
                ('kab', models.CharField(blank=True, max_length=100)),
                ('jalan', models.TextField(blank=True)),
                ('rt', models.CharField(blank=True, max_length=10)),
                ('rw', models.CharField(blank=True, max_length=10)),
                ('desa', models.CharField(blank=True, max_length=100)),
                ('kecamatan', models.CharField(blank=True, max_length=100)),
                ('provinsi', models.CharField(blank=True, max_length=100)),
                ('akta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pengurus_set', to='core.aktapt')),
            ],
            options={
                'db_table': 'pengurus',
            },
        ),
    ]
