# Generated by Django 5.2.12 on 2026-04-08 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aktapt',
            name='jenis_akta',
            field=models.CharField(choices=[('PT_MAROS', 'PT NOT MAROS'), ('PT_PALU', 'PT NOT PALU')], default='PT_MAROS', max_length=50),
        ),
    ]
