# Generated by Django 5.2.12 on 2026-04-08 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_aktapt_jenis_akta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pengurus',
            name='saham_persen',
            field=models.IntegerField(default=0),
        ),
    ]
