# Generated by Django 5.2.12 on 2026-04-09 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_pengurus_saham_persen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aktapt',
            name='jenis_akta',
            field=models.CharField(choices=[('PT_MAROS', 'PT NOT MAROS'), ('PT_PALU', 'PT NOT PALU'), ('CV_PALU', 'CV NOT PALU')], default='PT_MAROS', max_length=50),
        ),
    ]
