# Generated by Django 5.2.12 on 2026-04-09 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_aktapt_jenis_akta'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengurus',
            name='gelar_belakang',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pengurus',
            name='gelar_depan',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
