# Generated by Django 5.2.12 on 2026-04-09 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_pengurus_gelar_belakang_pengurus_gelar_depan'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengurus',
            name='gelar_singkat',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
