# Generated by Django 5.2.12 on 2026-04-16 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_aktapt_jenis_akta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aktapt',
            name='jenis_akta',
            field=models.CharField(choices=[('PT_MAROS', 'PT NOT MAROS'), ('PT_PALU', 'PT NOT PALU'), ('CV_PALU', 'CV NOT PALU'), ('PT_TANGSEL', 'PT NOT TANGSEL'), ('CV_MAROS', 'CV NOT MAROS')], default='PT_MAROS', max_length=50),
        ),
    ]
