# Generated by Django 5.2.12 on 2026-04-16 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_aktapt_jenis_akta'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengurus',
            name='nppw',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='aktapt',
            name='jenis_akta',
            field=models.CharField(choices=[('PT_MAROS', 'PT NOT MAROS'), ('PT_PALU', 'PT NOT PALU'), ('CV_PALU', 'CV NOT PALU'), ('PT_TANGSEL', 'PT NOT TANGSEL'), ('CV_MAROS', 'CV NOT MAROS'), ('PT_PERORANGAN', 'PT PERORANGAN')], default='PT_MAROS', max_length=50),
        ),
    ]
