# Generated by Django 5.2.12 on 2026-04-27 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_aktapt_jenis_akta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pengurus',
            old_name='nppw',
            new_name='npwp',
        ),
    ]
