# Generated by Django 5.2.12 on 2026-04-28 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_nppw_pengurus_npwp'),
    ]

    operations = [
        migrations.AddField(
            model_name='aktapt',
            name='kantor_kepaniteraan',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
