# Generated by Django 5.2.12 on 2026-04-28 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_aktapt_kantor_kepaniteraan'),
    ]

    operations = [
        migrations.AddField(
            model_name='aktapt',
            name='kota_kepaniteraan',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='aktapt',
            name='tipe_kepaniteraan',
            field=models.CharField(blank=True, default='Kota', max_length=20),
        ),
    ]
