# Generated by Django 5.2.12 on 2026-04-29 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_aktapt_kota_kepaniteraan_aktapt_tipe_kepaniteraan'),
    ]

    operations = [
        migrations.AddField(
            model_name='aktapt',
            name='persen_modal_disetor',
            field=models.IntegerField(default=100),
        ),
    ]
