# Generated by Django 5.2.12 on 2026-05-04 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_aktapt_persen_modal_disetor'),
    ]

    operations = [
        migrations.AddField(
            model_name='aktapt',
            name='provinsi_yayasan',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pengurus',
            name='is_pendiri',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pengurus',
            name='kategori_yayasan',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='aktapt',
            name='jenis_akta',
            field=models.CharField(choices=[('PT_MAROS', 'PT NOT MAROS'), ('PT_PALU', 'PT NOT PALU'), ('CV_PALU', 'CV NOT PALU'), ('PT_TANGSEL', 'PT NOT TANGSEL'), ('CV_MAROS', 'CV NOT MAROS'), ('CV_TANGSEL', 'CV NOT TANGSEL'), ('PT_PERORANGAN', 'PT PERORANGAN'), ('YAYASAN_TANGSEL', 'YAYASAN NOT TANGSEL')], default='PT_MAROS', max_length=50),
        ),
    ]
