# Generated by Django 5.2.12 on 2026-05-11 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_aktapt_provinsi_yayasan_pengurus_is_pendiri_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aktapt',
            name='jenis_akta',
            field=models.CharField(choices=[('PT_MAROS', 'PT NOT MAROS'), ('PT_PALU', 'PT NOT PALU'), ('CV_PALU', 'CV NOT PALU'), ('PT_TANGSEL', 'PT NOT TANGSEL'), ('CV_MAROS', 'CV NOT MAROS'), ('CV_TANGSEL', 'CV NOT TANGSEL'), ('PT_PERORANGAN', 'PT PERORANGAN'), ('YAYASAN_TANGSEL', 'YAYASAN NOT TANGSEL'), ('PT_MOROWALI', 'PT NOT MOROWALI')], default='PT_MAROS', max_length=50),
        ),
    ]
