# Generated by Django 5.2.12 on 2026-05-18 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_aktapt_jenis_akta'),
    ]

    operations = [
        migrations.AddField(
            model_name='aktapt',
            name='desa_cv',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='aktapt',
            name='kecamatan_cv',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
