# Generated by Django 5.2.12 on 2026-05-26 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_aktapt_jenis_akta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aktapt',
            name='jenis_akta',
            field=models.CharField(choices=[('PT_MAROS', 'PT NOT MAROS'), ('PT_PALU', 'PT NOT PALU'), ('CV_PALU', 'CV NOT PALU'), ('PT_TANGSEL', 'PT NOT TANGSEL'), ('CV_MAROS', 'CV NOT MAROS'), ('CV_TANGSEL', 'CV NOT TANGSEL'), ('PT_PERORANGAN', 'PT PERORANGAN'), ('YAYASAN_TANGSEL', 'YAYASAN NOT TANGSEL'), ('YAYASAN_MAROS', 'YAYASAN NOT MAROS'), ('YAYASAN_SOPPENG', 'YAYASAN NOT SOPPENG'), ('PT_MOROWALI', 'PT NOT MOROWALI'), ('CV_MOROWALI', 'CV NOT MOROWALI'), ('CV_SOPPENG', 'CV NOT SOPPENG'), ('PT_SOPPENG', 'PT NOT SOPPENG')], default='PT_MAROS', max_length=50),
        ),
    ]
