# Generated by Django 5.2.12 on 2026-06-08 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_aktapt_jenis_akta'),
    ]

    operations = [
        migrations.AddField(
            model_name='aktapt',
            name='desa_pt',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='aktapt',
            name='jalan_pt',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aktapt',
            name='kecamatan_pt',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='aktapt',
            name='provinsi_pt',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='aktapt',
            name='rt_pt',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='aktapt',
            name='rw_pt',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='aktapt',
            name='tipe_kab_pt',
            field=models.CharField(blank=True, default='Kota', max_length=20),
        ),
    ]
