# Generated by Django 5.2.12 on 2026-06-10 02:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_aktapt_desa_pt_aktapt_jalan_pt_aktapt_kecamatan_pt_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aktapt',
            name='is_draft_final_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aktapt',
            name='is_surat_kuasa_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aktapt',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='akta_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
