# Generated by Django 5.2.12 on 2026-06-10 02:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_aktapt_is_draft_final_generated_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aktapt',
            name='draft_final_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='draft_final_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aktapt',
            name='surat_kuasa_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surat_kuasa_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
