# Generated by Django 5.2.12 on 2026-06-10 03:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_aktapt_draft_final_user_aktapt_surat_kuasa_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftUserStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_lengkap', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('akta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_statuses', to='core.aktapt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('akta', 'user')},
            },
        ),
    ]
