# Generated by Django 5.2.12 on 2026-06-10 03:50

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_draftuserstatus'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='draftuserstatus',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='draftuserstatus',
            name='date_recorded',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='draftuserstatus',
            unique_together={('akta', 'user', 'date_recorded')},
        ),
    ]
