# Generated by Django 5.2.12 on 2026-06-11 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_draftuserstatus_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aktapt',
            name='draft_final_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aktapt',
            name='surat_kuasa_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
