# Generated by Django 5.2.12 on 2026-06-16 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_aktapt_draft_final_generated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aktapt',
            name='pos_pt',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
