# Generated by Django 5.2.12 on 2026-06-21 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_aktapt_jenis_akta'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftuserstatus',
            name='is_revisi',
            field=models.BooleanField(default=False),
        ),
    ]
