# Generated by Django 5.2.12 on 2026-06-21 06:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_draftuserstatus_is_revisi'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='draftuserstatus',
            unique_together={('akta', 'user')},
        ),
    ]
