# Generated by Django 5.2.12 on 2026-07-31 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_pengurus_ktp_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='aktapt',
            name='email_pt',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='aktapt',
            name='password_email_pt',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='aktapt',
            name='telp_pt',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='pengurus',
            name='email',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='pengurus',
            name='no_hp',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
