# Generated by Django 5.2.12 on 2026-08-07 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_aktapt_email_pt_aktapt_password_email_pt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengurus',
            name='npwp_urls',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
