# Generated by Django 5.2.17 on 2026-09-21 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_pengurus_npwp_urls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aktapt',
            name='jenis_akta',
            field=models.CharField(choices=[('PT_PERORANGAN', 'PT PERORANGAN')], default='PT_PERORANGAN', max_length=50),
        ),
    ]
