"""
Django settings for velloscript project.

Generated by 'django-admin startproject' using Django 5.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

BASE_DIR = Path(__file__).resolve().parent.parent
# override=False: environment variable dari platform (Vercel) menang atas .env.
# .env hanya dipakai sebagai fallback untuk pengembangan lokal.
load_dotenv(BASE_DIR / '.env', override=False)

# Dipakai hanya untuk menandatangani token CSRF. Tidak ada akun, sesi, atau
# data pengguna di server, jadi nilai bawaan di repo sudah memadai dan
# aplikasi bisa dideploy tanpa environment variable apa pun.
SECRET_KEY = os.environ.get('SECRET_KEY', 'velloscript-ptp-csrf-key-9f2c41ab7de05836')
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

# Host: default mengizinkan domain Vercel + localhost. Bisa ditimpa lewat env ALLOWED_HOSTS.
# Tidak ada akun maupun data pengguna di server, jadi tidak ada yang perlu
# dilindungi lewat pembatasan Host. Dibiarkan terbuka supaya deploy ke domain
# mana pun langsung jalan tanpa setting.
ALLOWED_HOSTS = ['*']

CSRF_TRUSTED_ORIGINS = [
    'https://*.vercel.app',
    'http://127.0.0.1:8000',
    'http://localhost:8000',
    'http://127.0.0.1:8001',
    'http://localhost:8001',
]
# Domain produksi sendiri, mis. CSRF_TRUSTED_ORIGINS=https://draft.contoh.id
CSRF_TRUSTED_ORIGINS += [o.strip() for o in os.environ.get('CSRF_TRUSTED_ORIGINS', '').split(',') if o.strip()]

# Vercel mengakhiri TLS di proxy-nya; tanpa ini Django menganggap request-nya HTTP.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# Application definition

INSTALLED_APPS = [
    # auth, contenttypes, sessions, dan messages dihapus: semuanya butuh
    # database, sementara aplikasi ini tidak memakai database sama sekali.
    'django.contrib.staticfiles',
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.common.CommonMiddleware',
    # CSRF tetap aktif; token-nya berbasis cookie, tidak butuh session.
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'velloscript.middleware.SecurityHeadersMiddleware',
]

ROOT_URLCONF = 'velloscript.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
            ],
        },
    },
]

WSGI_APPLICATION = 'velloscript.wsgi.application'


# ==============================================================================
# TANPA DATABASE
# ==============================================================================
# Draft disimpan di browser pengguna (localStorage), bukan di server.
# DATABASES sengaja kosong supaya tidak ada satu pun bagian yang diam-diam
# mencoba menulis ke disk — di serverless filesystem-nya read-only.
DATABASES = {}


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Makassar'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'
# CATATAN: STATICFILES_STORAGE dihapus di Django 5.1, jadi harus lewat STORAGES.
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        # Sengaja TANPA manifest: kalau staticfiles.json hilang atau basi,
        # varian Manifest membuat seluruh halaman 500. Versi ini tetap
        # mengompresi tapi gagal dengan anggun.
        'BACKEND': 'whitenoise.storage.CompressedStaticFilesStorage',
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ==============================================================================
# PENGATURAN KEAMANAN (MITIGASI OWASP ZAP)
# ==============================================================================

# 1. Cookie Security (Mencegah XSS membaca sesi)
CSRF_COOKIE_HTTPONLY = True

# 2. Cookie Secure (aktif di produksi; set COOKIE_SECURE=False untuk dev di http://localhost)
# Hanya cookie CSRF yang tersisa. Di lokal (DEBUG) harus non-secure supaya
# http://localhost tetap bisa mengirim form; di produksi selalu secure.
CSRF_COOKIE_SECURE = not DEBUG

# 3. Pengaturan lainnya diurus oleh custom middleware di velloscript/middleware.py